site_name: OSDF Documentation
site_url: https://docs.osdf.osg-htc.org
repo_name: null
theme:
  name: material
  logo: assets/OSG_Logo.svg
  favicon: assets/OSG_Logo.png
  custom_dir: overrides
  icon:
    admonition:
      halt: material/hand-back-left
      pro-tip: material/brain

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
  - meta
  - pymdownx.details
  - toc:
      permalink: True
  - footnotes

extra_css:
  - stylesheets/code-highlight.css
  - stylesheets/osg.css

nav:
  - Home:                           index.md
